FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --omit=dev

COPY server.js ./
COPY routes ./routes
COPY views ./views
COPY public ./public

ENV PORT=4173
EXPOSE 4173

CMD ["node", "server.js"]
