FROM node:18-alpine

WORKDIR /app

# Copy urusan dependensi dulu
COPY package*.json ./
RUN npm ci --omit=dev

# Copy semua file (kecuali yang ada di .dockerignore)
COPY . .

ENV PORT=4173
EXPOSE 4173

# Pake node biasa di Dockerfile, nanti kita timpa pas Run
CMD ["node", "server.js"]